---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-abcall-incidentes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-abcall-incidentes-deployment
  template:
    metadata:
      labels:
        app: ms-abcall-incidentes-deployment
    spec:
      containers:
        - name: ms-abcall-incidentes-deployment
          image: IMAGE_TO_REPLACE
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "2Gi"
          readinessProbe:
            httpGet:
              path: /service/abcall/incidentes/v1/ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /service/abcall/incidentes/v1/ping
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ms-abcall-incidentes-service
  annotations:
    cloud.google.com/backend-config: '{"default": "health-check-config-incidentes"}'
spec:
  selector:
    app: ms-abcall-incidentes-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-abcall-incidentes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-abcall-incidentes-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75