---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-abcall-incidentes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-abcall-incidentes-deployment
  template:
    metadata:
      labels:
        app: ms-abcall-incidentes-deployment
    spec:
      containers:
        - name: ms-abcall-incidentes-deployment
          image: IMAGE_TO_REPLACE
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ms-abcall-incidentes-service
spec:
  selector:
    app: ms-abcall-incidentes-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-abcall-incidentes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-abcall-incidentes-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75