---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-abcall-agentes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-abcall-agentes-deployment
  template:
    metadata:
      labels:
        app: ms-abcall-agentes-deployment
    spec:
      containers:
        - name: ms-abcall-agentes-deployment
          image: IMAGE_TO_REPLACE
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "1000m"
              ephemeral-storage: "2Gi"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -XX:InitialRAMPercentage=50.0
                -XX:MaxRAMPercentage=75.0
                -XX:+UseG1GC
                -Xmx1536m
                -XX:+HeapDumpOnOutOfMemoryError
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://127.0.0.1:5432/agentes
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          readinessProbe:
            httpGet:
              path: /service/abcall/agentes/v1/ping
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /service/abcall/agentes/v1/ping
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          command:
            - "/cloud_sql_proxy"
            - "abcall-uniandes-g18a:us-central1:postgresql"
          volumeMounts:
            - name: cloud-sql-proxy-sa-key-volume
              mountPath: /secrets/service_account.json
              subPath: service_account.json
              readOnly: true
          env:
            - name: GOOGLE_APPLICATIONS_CREDENTIALS
              value: /secrets/service_account.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
      volumes:
        - name: cloud-sql-proxy-sa-key-volume
          secret:
            secretName: cloud-sql-proxy-sa-key
---
apiVersion: v1
kind: Service
metadata:
  name: ms-abcall-agentes-service
  annotations:
    cloud.google.com/backend-config: '{"default": "health-check-config-agentes"}'
spec:
  selector:
    app: ms-abcall-agentes-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-abcall-agentes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-abcall-agentes-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75