apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: health-check-config
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /service/abcall/agentes/v1/ping
    port: 8080