swagger: '2.0'
info:
  title: ABCALL API Gateway
  description: API Gateway para todos los microservicios de ABCALL
  version: 1.0.0
host: abcall-api.endpoints.abcall-uniandes-g18a.cloud.goog
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /service/abcall/auth/v1/ping:
    get:
      summary: Valida el estado del microservicio de autenticación
      operationId: pingAuth
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/auth/v1/ping
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/agentes/v1/ping:
    get:
      summary: Valida el estado del microservicio de agentes
      operationId: pingAgentes
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/agentes/v1/ping
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/clientes/v1/ping:
    get:
      summary: Valida el estado del microservicio de clientes
      operationId: pingClientes
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/clientes/v1/ping
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/incidentes/v1/ping:
    get:
      summary: Valida el estado del microservicio de incidentes
      operationId: pingIncidentes
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/ping
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/auth/v1/login:
    post:
      summary: Permite la autenticación de un usuario
      operationId: autenticarUsuario
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/auth/v1/login
      parameters:
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
    options:
      summary: CORS preflight para autenticar un usuario
      operationId: corsAutenticarUsuario
      responses:
        '204':
          description: Respuesta preflight CORS exitosa
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/auth/v1/login

  /service/abcall/auth/v1/refrescar:
    post:
      summary: Permite la actualización del token de un usuario
      operationId: refrescarToken
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/auth/v1/refrescar
      parameters:
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
    options:
      summary: CORS preflight para autenticar un usuario
      operationId: corsRefrescarToken
      responses:
        '204':
          description: Respuesta preflight CORS exitosa
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/auth/v1/refrescar

  /service/abcall/agentes/v1/autenticar:
    post:
      summary: Permite la autenticación de un agente
      operationId: autenticarAgente
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/agentes/v1/autenticar
      parameters:
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
    options:
      summary: CORS preflight para autenticar cliente
      operationId: corsAutenticarAgente
      responses:
        '204':
          description: Respuesta preflight CORS exitosa
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/agentes/v1/autenticar

  /service/abcall/agentes/v1/tiposDocumento:
    get:
      summary: Retorna la lista de tipos de documento
      operationId: listarTiposDocumentoAgente
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/agentes/v1/tiposDocumento
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/clientes/v1/registrar:
    post:
      summary: Permite el registro de un cliente
      operationId: registrarCliente
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/clientes/v1/registrar
      parameters:
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '201':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
    options:
      summary: CORS preflight para registrar cliente
      operationId: corsRegistrarCliente
      responses:
        '204':
          description: Respuesta preflight CORS exitosa
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/clientes/v1/registrar

  /service/abcall/clientes/v1/autenticar:
    post:
      summary: Permite la autenticación de un cliente
      operationId: autenticarCliente
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/clientes/v1/autenticar
      parameters:
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
    options:
      summary: CORS preflight para autenticar cliente
      operationId: corsAutenticarCliente
      responses:
        '204':
          description: Respuesta preflight CORS exitosa
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/clientes/v1/autenticar

  /service/abcall/clientes/v1/validarUsuario:
    get:
      summary: Permite la validación de un usuario de un cliente
      operationId: validarUsuario
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/clientes/v1/validarUsuario
      parameters:
        - name: numeroDocumentoCliente
          in: path
          required: true
          type: string
          description: Número de documento del cliente
        - name: tipoDocumentoUsuario
          in: path
          required: true
          type: string
          description: Tipo de documento del usuario
        - name: numeroDocumentoUsuario
          in: path
          required: true
          type: string
          description: Número de documento del usuario
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/clientes/v1/listar:
    get:
      summary: Retorna la lista de clientes en estado activo
      operationId: listarClientes
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/clientes/v1/listar
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/clientes/v1/tiposDocumento:
    get:
      summary: Retorna la lista de tipos de documento
      operationId: listarTiposDocumentoUsuario
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/clientes/v1/tiposDocumento
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/incidentes/v1/crear:
    post:
      summary: Permite la creación de un incidente
      operationId: crearIncidente
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/crear
      parameters:
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '201':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
    options:
      summary: CORS preflight para crear incidente
      operationId: corsCrearIncidente
      responses:
        '204':
          description: Respuesta preflight CORS exitosa
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/crear

  /service/abcall/incidentes/v1/consultar:
    post:
      summary: Permite la consulta de incidentes
      operationId: consultarIncidentes
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/consultar
      parameters:
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
    options:
      summary: CORS preflight para consultar incidentes
      operationId: corsConsultarIncidentes
      responses:
        '204':
          description: Respuesta preflight CORS exitosa
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/consultar

  /service/abcall/incidentes/v1/consultarDetalle:
    get:
      summary: Permite la consulta de detalles de un incidente
      operationId: consultarDetalleIncidente
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/consultarDetalle
      parameters:
        - name: idIncidente
          in: path
          required: true
          type: string
          description: ID del incidente
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/incidentes/v1/actualizar:
    put:
      summary: Permite la actualización de un incidente
      operationId: actualizarIncidente
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/actualizar
      parameters:
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
    options:
      summary: CORS preflight para actualizar incidente
      operationId: corsActualizarIncidente
      responses:
        '204':
          description: Respuesta preflight CORS exitosa
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/actualizar

# Sección para CORS y seguridad
x-google-management:
  metrics:
    - name: "requests"
      displayName: "Requests"
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      - name: "requests-per-project"
        metric: "requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 10000

# Configuración de CORS
x-google-endpoints:
  - name: abcall-api.endpoints.abcall-uniandes-g18a.cloud.goog
    allowCors: true

x-google-cors:
  allow-origins:
    - https://abcall-932696033849.us-central1.run.app
  allow-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow-headers:
    - Content-Type
    - Authorization
    - X-Requested-With
  expose-headers:
    - Content-Length
    - X-Kuma-Revision
  max-age: 3600
  allow-credentials: true