swagger: '2.0'
info:
  title: ABCALL API Gateway
  description: API Gateway para todos los microservicios de ABCALL
  version: 1.0.0
host: abcall-api.endpoints.abcall-uniandes-g18a.cloud.goog
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /service/abcall/{service}/v1/{path}:
    get:
      summary: Operaciones GET para cualquier microservicio
      operationId: genericGet
      x-google-backend:
        address: http://abcall-backend.abcall-internal.com/service/abcall/{service}/v1/{path}
      parameters:
        - name: service
          in: path
          required: true
          type: string
          description: Nombre del microservicio (agentes, clientes, ia, incidentes, reporteria, auth)
        - name: path
          in: path
          required: true
          type: string
          description: Ruta específica del endpoint
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

    post:
      summary: Operaciones POST para cualquier microservicio
      operationId: genericPost
      x-google-backend:
        address: http://abcall-backend.abcall-internal.com/service/abcall/{service}/v1/{path}
      parameters:
        - name: service
          in: path
          required: true
          type: string
          description: Nombre del microservicio (agentes, clientes, ia, incidentes, reporteria, auth)
        - name: path
          in: path
          required: true
          type: string
          description: Ruta específica del endpoint
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

    put:
      summary: Operaciones PUT para cualquier microservicio
      operationId: genericPut
      x-google-backend:
        address: http://abcall-backend.abcall-internal.com/service/abcall/{service}/v1/{path}
      parameters:
        - name: service
          in: path
          required: true
          type: string
          description: Nombre del microservicio (agentes, clientes, ia, incidentes, reporteria, auth)
        - name: path
          in: path
          required: true
          type: string
          description: Ruta específica del endpoint
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

# Sección para CORS y seguridad
x-google-management:
  metrics:
    - name: "requests"
      displayName: "Requests"
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      - name: "requests-per-project"
        metric: "requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 10000

# Configuración de CORS
x-google-endpoints:
  - name: abcall-api.endpoints.abcall-uniandes-g18a.cloud.goog
    allowCors: true