swagger: '2.0'
info:
  title: ABCALL API Gateway
  description: API Gateway para todos los microservicios de ABCALL
  version: 1.0.0
host: abcall-api.endpoints.abcall-uniandes-g18a.cloud.goog
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /service/abcall/auth/v1/ping:
    get:
      summary: Valida el estado del microservicio de autenticación
      operationId: genericGet
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/auth/v1/ping
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/agentes/v1/ping:
    get:
      summary: Valida el estado del microservicio de agentes
      operationId: genericGet
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/agentes/v1/ping
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/clientes/v1/ping:
    get:
      summary: Valida el estado del microservicio de clientes
      operationId: genericGet
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/clientes/v1/ping
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/ia/v1/ping:
    get:
      summary: Valida el estado del microservicio de IA
      operationId: genericGet
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/ia/v1/ping
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/incidentes/v1/ping:
    get:
      summary: Valida el estado del microservicio de incidentes
      operationId: genericGet
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/ping
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/reporteria/v1/ping:
    get:
      summary: Valida el estado del microservicio de reportería
      operationId: genericGet
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/reporteria/v1/ping
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/clientes/v1/authenticate:
    post:
      summary: Permite la autenticación de un cliente
      operationId: genericPost
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/clientes/v1/authenticate
      parameters:
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/incidentes/v1/crear:
    post:
      summary: Permite la creación de un incidente
      operationId: genericPost
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/crear
      parameters:
        - name: body
          in: body
          schema:
            type: object
          description: Cuerpo de la solicitud
      responses:
        '201':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/incidentes/v1/consultar:
    get:
      summary: Valida el estado del microservicio de reportería
      operationId: genericGet
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/consultar
      parameters:
        - name: tipoDocUsuario
          in: path
          required: true
          type: string
          description: Tipo de documento del usuario
        - name: numeroDocUsuario
          in: path
          required: true
          type: string
          description: Número de documento del usuario
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

  /service/abcall/incidentes/v1/consultarDetalle:
    get:
      summary: Valida el estado del microservicio de reportería
      operationId: genericGet
      x-google-backend:
        address: http://34.144.226.68.nip.io/service/abcall/incidentes/v1/consultarDetalle
      parameters:
        - name: idIncidente
          in: path
          required: true
          type: string
          description: ID del incidente
      responses:
        '200':
          description: Operación exitosa
        '206':
          description: Contenido parcial
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

# Sección para CORS y seguridad
x-google-management:
  metrics:
    - name: "requests"
      displayName: "Requests"
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      - name: "requests-per-project"
        metric: "requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 10000

# Configuración de CORS
x-google-endpoints:
  - name: abcall-api.endpoints.abcall-uniandes-g18a.cloud.goog
    allowCors: true