---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-abcall-reporteria-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-abcall-reporteria-deployment
  template:
    metadata:
      labels:
        app: ms-abcall-reporteria-deployment
    spec:
      containers:
        - name: ms-abcall-reporteria-deployment
          image: IMAGE_TO_REPLACE
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "1000m"
              ephemeral-storage: "2Gi"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -XX: InitialRAMPercentage=50.0
                -XX: MaxRAMPercentage=75.0
                -XX: +UseG1GC
                -Xmx1536m
                -XX: +HeapDumpOnOutOfMemoryError
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud"
          readinessProbe:
            httpGet:
              path: /service/abcall/ia/v1/ping
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /service/abcall/ia/v1/ping
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ms-abcall-reporteria-service
  annotations:
    cloud.google.com/backend-config: '{"default": "health-check-config-reporteria"}'
spec:
  selector:
    app: ms-abcall-reporteria-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-abcall-reporteria-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-abcall-reporteria-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75