name: Microservices CI/CD with Java 21 and Detailed K8s Deployment

on:
  pull_request:
    branches: [ main, release, develop ]
  pull_request_target:
    types:
      - closed

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  JAVA_VERSION: '21'

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Validate PR
        run: |
          BASE="${{ github.base_ref }}"
          HEAD="${{ github.head_ref }}"
          if [[ $HEAD == feat/* && $BASE == "develop" ]]; then
            echo "Valid PR: feat to develop"
          elif [[ $BASE == "release" && $HEAD == "develop" ]] || [[ $BASE == "main" && $HEAD == "release" ]]; then
            echo "Valid PR: develop to release or release to main"
          else
            echo "Invalid PR combination"
            exit 1
          fi

  test-and-analyze:
    needs: validate-pr
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'feat/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - service: MSAgentes
          sonar_project_id: agentes
        - service: MSClientes
          sonar_project_id: clientes
        - service: MSIA
          sonar_project_id: ia
        - service: MSIncidentes
          sonar_project_id: incidentes
        - service: MSReporteria
          sonar_project_id: reporteria
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Grant execute permission for mvnw
        run: chmod +x ./${{ matrix.service }}/mvnw
      - name: Build, test, and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd ${{ matrix.service }}
          ./mvnw clean verify org.jacoco:jacoco-maven-plugin:report sonar:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}${{ matrix.sonar_project_id }} \
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.java.source=${{ env.JAVA_VERSION }} \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      - name: Build, analyze, and check coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd ${{ matrix.service }}
          echo "Running Maven command for ${{ matrix.service }}..."
          ./mvnw clean verify org.jacoco:jacoco-maven-plugin:report sonar:sonar \
            -Dsonar.projectKey=com.abcall.${{ matrix.sonar_project_id }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=https://sonarcloud.io
          MAVEN_EXIT_CODE=$?
          echo "Maven exit code for ${{ matrix.service }}: $MAVEN_EXIT_CODE"
          if [ $MAVEN_EXIT_CODE -eq 0 ]; then
            echo "Build successful and test coverage meets or exceeds minimum threshold for ${{ matrix.service }}"
          else
            echo "Build failed or test coverage below minimum threshold for ${{ matrix.service }}"
            exit 1
          fi

  build-and-push:
    needs: validate-pr
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    strategy:
      matrix:
        include:
          - artifact-registry: ms-agentes
            service: MSAgentes
          - artifact-registry: ms-clientes
            service: MSClientes
          - artifact-registry: ms-ia
            service: MSIA
          - artifact-registry: ms-incidentes
            service: MSIncidentes
          - artifact-registry: ms-reporteria
            service: MSReporteria
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Grant execute permission for mvnw
        run: chmod +x ./${{ matrix.service }}/mvnw
      - name: Build with Maven
        run: |
          cd ${{ matrix.service }}
          ./mvnw package -DskipTests
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure Docker
        run: gcloud auth configure-docker gcr.io --quiet
      - name: Build and Push Docker image
        env:
          IMAGE: ${{ matrix.artifact-registry }}
        run: |
          cd ${{ matrix.service }}
          docker build --build-arg JAVA_VERSION=${{ env.JAVA_VERSION }} -t gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA .
          docker push gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    strategy:
      matrix:
        include:
          - module: MSAgentes
            yaml_name: agentes
          - module: MSClientes
            yaml_name: clientes
          - module: MSIA
            yaml_name: ia
          - module: MSIncidentes
            yaml_name: incidentes
          - module: MSReporteria
            yaml_name: reporteria
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Get GKE Credentials with Timeout
        run: |
          timeout 600s gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE || echo "Command timed out after 600 seconds"
      - name: Update image in Kubernetes manifest
        run: |
          sed -i 's|IMAGE_TO_REPLACE|gcr.io/${{ env.PROJECT_ID }}/ms-${{ matrix.yaml_name }}:${{ github.sha }}|g' ${{ matrix.module }}/k8s/ms-abcall-${{ matrix.yaml_name }}.yaml
      - name: Deploy Module to GKE
        run: |
          kubectl apply -f ${{ matrix.module }}/k8s/ms-abcall-${{ matrix.yaml_name }}.yaml
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/ms-abcall-clientes-deployment
          kubectl get services -o wide | grep ms-abcall-clientes-service
          kubectl get hpa ms-abcall-clientes-hpa

  update-ingress:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
      - name: Update and Apply Ingress
        run: |
          kubectl apply -f k8s/abcall-ingress.yaml
      - name: Verify Ingress
        run: |
          kubectl get ingress
          kubectl describe ingress abcall-ingress

  cleanup-feature-branch:
    needs: test-and-analyze
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feat/')
    steps:
      - name: Delete feature branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}