name: Microservices CI/CD with Java 21 and Detailed K8s Deployment

on:
  pull_request:
    branches: [ main, release, develop ]
    types: [ opened, synchronize, reopened ]
  pull_request_target:
    types: [ closed ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  JAVA_VERSION: '21'

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Validate PR
        run: |
          BASE="${{ github.base_ref }}"
          HEAD="${{ github.head_ref }}"
          if [[ $HEAD == feat/* && $BASE == "develop" ]]; then
            echo "Valid PR: feat to develop"
          elif [[ $BASE == "release" && $HEAD == "develop" ]] || [[ $BASE == "main" && $HEAD == "release" ]]; then
            echo "Valid PR: develop to release or release to main"
          else
            echo "Invalid PR combination"
            exit 1
          fi

  test-and-analyze:
    needs: validate-pr
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'feat/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: MSAgentes
            sonar_project_id: -MSAgentes
          - service: MSClientes
            sonar_project_id: -MSClientes
          - service: MSIA
            sonar_project_id: -MSIA
          - service: MSIncidentes
            sonar_project_id: -MSIncidentes
          - service: MSReporteria
            sonar_project_id: -MSReporteria
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Grant execute permission for mvnw
        run: chmod +x ./${{ matrix.service }}/mvnw
      - name: Build, test, and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd ${{ matrix.service }}
          ./mvnw clean verify org.jacoco:jacoco-maven-plugin:report sonar:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}${{ matrix.sonar_project_id }} \
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.java.source=${{ env.JAVA_VERSION }} \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          -Dsonar.qualitygate.wait=true
      - name: Check Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd ${{ matrix.service }}
          QUALITY_GATE_STATUS=$(curl -s -u ${SONAR_TOKEN}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}${{ matrix.sonar_project_id }}" | jq -r '.projectStatus.status')
          
          if [ "$QUALITY_GATE_STATUS" = "ERROR" ]; then
            echo "Quality Gate failed!"
            exit 1
          fi

  build-and-push:
    needs: validate-pr
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    strategy:
      matrix:
        include:
          - artifact-registry: ms-agentes
            service: MSAgentes
          - artifact-registry: ms-clientes
            service: MSClientes
          - artifact-registry: ms-ia
            service: MSIA
          - artifact-registry: ms-incidentes
            service: MSIncidentes
          - artifact-registry: ms-reporteria
            service: MSReporteria
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Grant execute permission for mvnw
        run: chmod +x ./${{ matrix.service }}/mvnw
      - name: Build with Maven
        run: |
          cd ${{ matrix.service }}
          ./mvnw package -DskipTests
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: Build and Push Docker image
        env:
          IMAGE: ${{ matrix.artifact-registry }}
        run: |
          cd ${{ matrix.service }}
          docker build --build-arg JAVA_VERSION=${{ env.JAVA_VERSION }} -t us-central1-docker.pkg.dev/$PROJECT_ID/microservices/$IMAGE:$GITHUB_SHA .
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/microservices/$IMAGE:$GITHUB_SHA

  deploy-backend-config:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
      - name: Apply BackendConfig
        run: |
          kubectl apply -f k8s/abcall-backend-config.yaml

  deploy-agentes:
    needs: deploy-backend-config
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Get GKE Credentials with Timeout
        run: |
          timeout 1200s gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE || echo "Command timed out after 1200 seconds"
      - name: Update image in Kubernetes manifest
        run: |
          sed -i 's|IMAGE_TO_REPLACE|us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/microservices/ms-agentes:${{ github.sha }}|g' MSAgentes/k8s/ms-abcall-agentes.yaml
      - name: Deploy Module to GKE
        run: |
          kubectl apply -f MSAgentes/k8s/ms-abcall-agentes.yaml
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/ms-abcall-agentes-deployment
          kubectl get services -o wide | grep ms-abcall-agentes-service
          kubectl get hpa ms-abcall-agentes-hpa

  deploy-clientes:
    needs: deploy-agentes
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Get GKE Credentials with Timeout
        run: |
          timeout 1200s gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE || echo "Command timed out after 1200 seconds"
      - name: Update image in Kubernetes manifest
        run: |
          sed -i 's|IMAGE_TO_REPLACE|us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/microservices/ms-clientes:${{ github.sha }}|g' MSClientes/k8s/ms-abcall-clientes.yaml
      - name: Deploy Module to GKE
        run: |
          kubectl apply -f MSClientes/k8s/ms-abcall-clientes.yaml
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/ms-abcall-clientes-deployment
          kubectl get services -o wide | grep ms-abcall-clientes-service
          kubectl get hpa ms-abcall-clientes-hpa

  deploy-ia:
    needs: deploy-clientes
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Get GKE Credentials with Timeout
        run: |
          timeout 1200s gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE || echo "Command timed out after 1200 seconds"
      - name: Update image in Kubernetes manifest
        run: |
          sed -i 's|IMAGE_TO_REPLACE|us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/microservices/ms-ia:${{ github.sha }}|g' MSIA/k8s/ms-abcall-ia.yaml
      - name: Deploy Module to GKE
        run: |
          kubectl apply -f MSIA/k8s/ms-abcall-ia.yaml
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/ms-abcall-ia-deployment
          kubectl get services -o wide | grep ms-abcall-ia-service
          kubectl get hpa ms-abcall-ia-hpa

  deploy-incidentes:
    needs: deploy-ia
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Get GKE Credentials with Timeout
        run: |
          timeout 1200s gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE || echo "Command timed out after 1200 seconds"
      - name: Update image in Kubernetes manifest
        run: |
          sed -i 's|IMAGE_TO_REPLACE|us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/microservices/ms-incidentes:${{ github.sha }}|g' MSIncidentes/k8s/ms-abcall-incidentes.yaml
      - name: Deploy Module to GKE
        run: |
          kubectl apply -f MSIncidentes/k8s/ms-abcall-incidentes.yaml
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/ms-abcall-incidentes-deployment
          kubectl get services -o wide | grep ms-abcall-incidentes-service
          kubectl get hpa ms-abcall-incidentes-hpa

  deploy-reporteria:
    needs: deploy-incidentes
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Get GKE Credentials with Timeout
        run: |
          timeout 1200s gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE || echo "Command timed out after 1200 seconds"
      - name: Update image in Kubernetes manifest
        run: |
          sed -i 's|IMAGE_TO_REPLACE|us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/microservices/ms-reporteria:${{ github.sha }}|g' MSReporteria/k8s/ms-abcall-reporteria.yaml
      - name: Deploy Module to GKE
        run: |
          kubectl apply -f MSReporteria/k8s/ms-abcall-reporteria.yaml
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/ms-abcall-reporteria-deployment
          kubectl get services -o wide | grep ms-abcall-reporteria-service
          kubectl get hpa ms-abcall-reporteria-hpa

  update-ingress:
    needs: deploy-reporteria
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
      - name: Update and Apply Ingress
        run: |
          kubectl apply -f k8s/abcall-ingress.yaml
      - name: Verify Ingress
        run: |
          kubectl get ingress
          kubectl describe ingress abcall-ingress